security_analysis_task:
  description: >
    Conduct a thorough research about each of the source code files in the input directory and identify the critical security issues.
  expected_output: >
    A list with bullet points of the most security issues found in each of the source code files in the input directory.
    List those security issues if exists in each files along with the file names in the order of their severity.
  agent: security_expert
